from sqlalchemy.orm import relationship
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, DateTime
from slackTables.base import Base

class Attachment(Base):
    __tablename__ = "attachments"
    id = Column(Integer, primary_key=True)
    title = Column(String)
    ts = Column(Integer)
    author_id = Column(String)
    author_subname = Column(String)
    author_name = Column(String)
    author_link = Column(String)
    author_icon = Column(String)
    mrkdwn_in = Column(String)
    color = Column(String)
    thumb_url = Column(String)
    thumb_width = Column(Integer)
    thumb_height = Column(Integer)
    from_url = Column(String)
    is_share = Column(Boolean)
    footer = Column(String)
    is_msg_unfurl = Column(Boolean)
    channel_id = Column(String)
    channel_name = Column(String)
    title_link = Column(String)
    fallback = Column(String)
    text = Column(String)
    blocks = relationship("AttachmentBlock", uselist=True, back_populates="attachment")
    fallback = Column(String)
    image_url = Column(String)
    from_url = Column(String)
    image_width = Column(Integer)
    image_height = Column(Integer)
    image_bytes = Column(Integer)
    service_icon = Column(String)
    service_name = Column(String)
    attachment_id = Column(Integer)
    original_url = Column(String)
    bot_id = Column(String)
    app_unfurl_url = Column(String)
    is_app_unfurl = Column(Boolean)
    service_url = Column(String)
    video_html = Column(String)
    video_html_width = Column(Integer)
    video_html_height = Column(Integer)
    fields = Column(String)
    pretext = Column(String)
    message_id = Column(Integer, ForeignKey("messages.id"))
    message = relationship("Message", back_populates="attachments")